### ISSUE TITLE
New floder feature question

### ISSUE THREAD

**Issue by FarmerChillax** [mjt233/saltedfishcloud-frontend#1]
every time i need to remove the cursor to the end of the line to delete the built-in text,  i think this experience is so bad.

i have a few suggestions that hope can be improved:

1. select all built-in text when user click the new floder button
2. the built-in text cursor maybe can placed on last
3. dont used built-in text

**Comment by FarmerChillax** [comment]
problem location:
![image](https://user-images.githubusercontent.com/48387781/145336898-2ae1d4a7-b9e2-4e3d-b762-99c325770a25.png)

**Comment by mjt233** [comment]
good，it will be implemented in the next version

**Comment by mjt233** [comment]
Has been implemented at master:ad9d2466ea350777c83efa07af5e5f5c4fa5bf16
